export const FETCH_PLAYERS = "players/FETCH_PLAYERS";
export const FETCH_PLAYERS_SUCCESS = "players/FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_ERROR = "players/FETCH_PLAYERS_ERROR";
export const SET_DISHONORS = "players/SET_DISHONORS";
export const SET_DISHONORS_SUCCESS = "players/SET_DISHONORS_SUCCESS";
export const SET_DISHONORS_ERROR = "players/SET_DISHONORS_ERROR";
